name: image_blur
description: "This Flutter package enables adding shimmer and blur effects to images. Apply these effects in circular and rectangular shapes, for both local and online images."
version: 1.0.9
homepage: https://github.com/SwanFlutter/image_blur
publish_to: none

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  fast_cached_network_image: ^1.2.9
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.8.2
  http: ^1.2.1
  image: ^4.2.0
  palette_generator: ^0.3.3+3
  image_blur_web:
    path: /Android/Pakege/image_blur_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
